name: CI - Products Service

on:
  push:
    paths:
      - "products-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”¹ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ”¹ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ðŸ”¹ Install dependencies
        working-directory: products-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ðŸ”¹ Lint Python code
        working-directory: products-service
        run: |
          pip install flake8
          flake8 app/main.py

      - name: ðŸ”¹ Build Docker image
        run: |
          docker build -t products-service:ci products-service
